name: ml-fundamentals

channels:
  - conda-forge
  - defaults
  
dependencies:
  - pip
  - pre_commit
  - python==3.9
  - python-dotenv
  - notebook==6.5.2
  - pandas==1.5.2 
  - numpy==1.23.4
  - tqdm==4.64.1
  - scikit-learn==
  - matplotlib==